version: 0.2

phases:
  install:
    runtime-versions:
      docker: 18 
  build:
    on-failure: ABORT
    commands:
      - echo Build started on `date`
      - echo Compiling the Node.js code
      - pwd
      - docker build ./Dockerfile
  post_build:
    commands:
      - echo Build completed on `date`

